### ISSUE TITLE
No module named 'int_quantization'

### ISSUE THREAD

**Issue by shooker531** [submission2019/cnn-quantization#13]
I've seen this as a previous issue but it was closed. I have access to the required HW but I am still encountering the error message shown below:

Traceback (most recent call last):
  File "inference/inference_sim.py", line 25, in <module>
    from pytorch_quantizer.quantization.inference.inference_quantization_manager import QuantizationManagerInference as QM
  File "/dcs/pg19/u1998253/Dissertation/cnn-quantization/inference/../pytorch_quantizer/quantization/inference/inference_quantization_manager.py", line 4, in <module>
    from pytorch_quantizer.quantization import qtypes
  File "/dcs/pg19/u1998253/Dissertation/cnn-quantization/inference/../pytorch_quantizer/quantization/qtypes/__init__.py", line 1, in <module>
    from .int_quantizer import int_quantizer
  File "/dcs/pg19/u1998253/Dissertation/cnn-quantization/inference/../pytorch_quantizer/quantization/qtypes/int_quantizer.py", line 4, in <module>
    import int_quantization
ModuleNotFoundError: No module named 'int_quantization'

**Comment by CSSFA123** [comment]
You forgot this part.

"Building cuda kernels for GEMMLOWP"

**Comment by 784582008** [comment]
> 
Hi, CSSFA123,how to do this："Building cuda kernels for GEMMLOWP".
